import bottleneck from "./images/article-images/bottleneck.png";
import van from "./images/article-images/van-life-crime.webp";
import pareto from "./images/article-images/pareto.gif";

let articleList = [
  {
    title: "Simplicity is a Bottleneck",
    paragraphs: [
      "Are people exaggerating, deceiving, or otherwise being delusional when they say that minimalism changed their life? It seems unlikely from the outside that changing the space a person lives in, or the way they go about their life, could have an impact on the real, core personality and characteristics of that person. For many, the merits of something like minimalism are only visible through practice. Like meditation, spirituality, and other types of eye-roll inducing new age pillars, practitioners ask the public for a leap of faith when trying to change their minds. Perhaps the best way to consider problems like this is with analogy, which can remove context and bias in order to get at the core of something. Luckily for us an analogy for minimalism exists in the world of biology – the Bottleneck Effect.",
      "The Bottleneck Effect describes the change which happens to a population (of animals, fungi, bacteria, whatever) after a sudden and disruptive change happens in their environment. To illustrate this phenomenon in a simple way, let’s imagine that there is a dog pound on an island somewhere in the Pacific Ocean. The dog pound has all types of dogs, including everything from pit bulls to chihuahuas to shih tzus. One day, a volcano erupts on the island, and lava is pouring down towards the pound. In a panic, islanders take the dogs from the pound and board them onto several ships which head to nearby islands, each only large enough to house a fraction of the total number of dogs. By chance, one of the boats fills with only chihuahuas, and heads to an island which is an hour boat ride away.",
      "On this new island, populated by only chihuahuas, every new generation of dog born will look like a chihuahua. Everything dog on this new island will be small, yappy, and soft. Even though these dog’s ancestors come from a much larger genetic pool, the bottleneck effect which their lineage experienced (the volcanic eruption) shrunk the variability in genetic possibilities for these dogs. Extrapolating this to the real world, the bottleneck effect is a big part of why species differ over time. In many cases the products of bottleneck events are populations that are appear to be entirely different than the populations that their ancestors. ",
      "image",
      "With that in mind, consider what the stated function of minimalism and simplicity movements. They serve as a self-imposed bottleneck which selects for things that are essential and meaningful. Rather than a volcano randomly selecting which traits make it to the future, minimalism selects for things which are meaningful. Things which are excessive and frivolous don’t make it through the bottleneck, which allows the meaningful things to blossom on the other end. When people reduce the size of their living space, the number of things they have to tend to, or the number of hours they spend at jobs they don’t enjoy, they have created a bottleneck that has removed a lot of junk in the population that is their daily life. Over time, new things fill the void left by the cutting out of things that aren’t essential. If one is careful about selecting based on meaning, time spent on cleaning their house that is too big can be used for something like meditation. These changes pile up over time, and, like a population that looks and feels incredibly different from before the Bottleneck event, a person can go through drastic changes as well. "
    ],
    image: bottleneck
  },
  {
    title: "NIMBYism",
    paragraphs: [
      "image",
      "Zack Griffin had a dream to be a professional skier. In his early 20s he felt that if he really wanted to pursue this passion, he would have to make some drastic changes in lifestyle and priorities. He opted for a risk. He moved into a motorhome, headed west, and took a minimum wage job where he could spend the rest of his time skiing. Nearly a decade later, after slowly building credentials, the gamble paid off and he became a full-time professional skier. To accommodate his transient and frugal lifestyle during this period, he built a 112 square foot tiny home which he was able to tow from mountain to mountain. With rent costs out of the way and no requirements for a fixed location, Zack was able to spend more time on the slopes and on whichever mountain he felt would be best at the time. ",
      "Zack’s tiny home garnered a lot of attention, and he quickly realized that the niche situation which he had designed the home for could be exported to many other people that were looking for something similar in their lives. As his skiing career waned, he started a company designing and building tiny homes. The company helped people that needed cheap, mobile, and comfortable housing which was comfortable enough to live in for long periods of time. After years of helping people escape their mortgages and give them flexibility, in 2016 Zack gave a TedX talk in which he laid out succinctly exactly why tiny houses work, “How many people work in jobs that you don’t feel completely inspired by, or maybe have had a dream that just felt a bit out of reach, or maybe you feel like you just don’t have enough time for yourself or your family? Because for those of us who live in tiny houses, the definition of a tiny house may be a home under 400 square feet, but how we see it is a tool to live a life that we choose. It’s a tool that we use to avoid the financial traps that leave so many people treading water. And once you put your need for space up against your need to achieve your dreams, the actual relevance of a tiny house becomes apparent.” ",
      "Zack now stars in a Netflix series called Tiny House Nation which follows him around the country as he builds tiny houses for couples and families. He is featured as the Moses of housing, guiding people out of the servitude of expensive mortgages and suffocating rent prices to a promise land of affordability and peace. Sure, the show is a little gimmicky, as such productions for general audiences are bound to be. They skip the antecedent to many of the client’s choice to select a tiny house, which is presumably a midnight screaming and crying bout over past due mortgages and frantic prayer for an easy way out of the hell which has consumed them. But it is a charming show, and Zack is genuinely confident that tiny houses can be a way forward and scale to fit the needs of the general population. He is convinced that this house style isn’t just an oddity in the history of architecture, saying, “The tiny house movement isn’t a fad based upon an infatuation with everything small. The tiny house movement is a response to these growing environmental factors that are only going to become more and more extreme in years to come. Many people are looking at these tiny homes as ways to address these new realities.”",
      "Over his years of work of helping people build something which often has such a profound impact on their lives, he has been discouraged to learn about the reception of tiny houses by the public. The people who live in tiny houses, and the droves of people who are utterly fascinated by them, absolutely love this movement. The unwelcome reception has instead come from the NIMBY, or Not in My Backyard, crowd, which puts up a strong and active resistance to having anything untraditional near their living space. This unofficial group encapsulates the housing boards, snooty neighbors, and property managers fearful of their investments which erect barriers to different styles of homes in their neighborhoods. ",
      "Zach stumbled upon a tool which can help people live their best lives, and not only has to do the hard job of convincing people that this could work for them, but then has to enter the bureaucratic nightmare of zoning regulations and city ordinances. It’s like winning the jackpot at a casino, only to have an earthquake impede your way out the door with your loot. Zach explains, “The hardest part about living in a tiny home is not how you pair down your shoe collection. Contrary to popular belief, the hardest part is navigating building codes and zoning requirements that really limit their creation.”",
      "For most of the stories in this book, the characters only have to deal with the downward gaze of polite society. They have to deal with snide remarks and an ostracizing attitude, which sucks, but can be brushed aside by stronger people. Housing alternatives come with a higher social price tag. The NIMBY crowd see their house are their store of wealth and largest asset and seeing someone nearby in a dwelling that’s cheaper (read better) scares and offends them. They protect their home values by lobbying local housing departments to enact ordinances for minimum housing size requirements, and other varieties red tape which severely hampers tiny home construction and parking. ",
      "In his book The Small House Book, Jay Shafer (a friend of Dee Williams who inspired her to build her tiny house) enumerates many of the hurdles which stand in the way of having a tiny house in a populated area. For starters, this kind of thing is only a concern in urban or suburban environments, rural locations rarely have stipulations preventing tiny homes, and many people in tiny homes choose to live further away from cities just to avoid the burden of zoning conflicts. According to Jay, the push for big houses as a norm and zoning requirements began in the 1970s and 1980s when the housing industry and banks wanted to find ways to make more profit per structure (10). These industries pushed for regulations setting minimum-size standards, and their stated purpose was to “preserve the high quality of living enjoyed in urban and suburban areas”.",
      "Now that these standards have solidified over time, changing them or living with them can be an uphill battle. Codes vary widely based on location, but solutions often revolve around finding loopholes, such as viewing your house as a “care-taker” home for a person who’s yard you may live in. The other option is to work within the system to enact change. Jay encourages people to work with housing departments, and to treat local officials as the helpful resource they want to be rather than an adversary. Showing them evidence of how much less wasteful a tiny house is, or that property values often go up rather than down when featured in a neighborhood (11) can sway officials to work to allow tiny homes in their districts. In some cases, these disputes have made their way through the court system, and several U.S. courts have found minimum-size standards to be unconstitutional. ",
      "Changes to allow for new housing solutions have to start with the public’s acceptance of a problem with the way things are. No one is calling for an upheaval and seizure of land or telling people they can’t live in a monster house if they so choose. But, minimum size standards for homes and the requirement of taking on a large debt burden to live in a comfortable house is precluding people like Zach and Jay from getting a larger segment of the population housing which works for them. Housing can be more mobile, vastly cheaper, and less wasteful if we just allow a little more experimentation. "
    ],
    image: van
  },
  {
    title: "Career Strategies for Creatives",
    paragraphs: [
      "Have you heard of the Pareto Distribution? Or maybe one of its synonyms like the 80-20 rule or the Matthew Principle? It’s a term coined by Italian civil engineer and economist Vilfredo Pareto to describe distributions which are exponential (5). A popular example, which has been discussed in detail in this book, is wealth inequality. If you mapped out every person in the US from smallest total assets ($0) to the largest amount of assets (Jeff Bezos at $161 billion), you wouldn’t see a straight line. Instead, there would be long tail with a sudden and sharp incline near the very end of the graph. Winner-take-all graphs like this are described as Pareto distributions, and this type of layout can be seen in all sorts of things from patterns in geophysics to plotting productivity for every employee at a large company.",
      "image",
      "This pattern is found ubiquitously when looking at success in creative fields. Think of Spotify streams for musicians as an example. Ed Sheeran’s “Shape of You” has a whopping 2.5 billion streams, yielding him royalty check of close to 11 million dollars for a single song. Contrast this to the average song on Spotify. Anyone can put a song on Spotify, and most of them have less than one hundred listens, which will give the artist almost to no money. Even very talented and creative artists have a very hard time getting by on their craft. It takes 336,169 streams per month on Spotify to even make minimum wage (6). This means that to ‘make it’, even modestly defining the term, requires commanding over a million minutes of human attention every month. How many people can realistically do that?",
      "The number of people who are successful in any creative field is vastly outweighed by the number of people who are creative or have talent in that field. For the vast majority of creative people the massive payday isn’t going to happen. The problem is, they can’t just stop looking at the world in a different way and choose a more ‘normal’ path in life. Their art isn’t something that can just be ignored or suppressed without major consequences, but pursuing their art has a very good chance of putting them in a position where they can’t pay the bills. It’s a hell of a catch-22. Psychologist Jordan Peterson explains in his lectures at University of Toronto that creative people, “don’t really have much choice in it. Because, if you are a creative person, it’s like a fruit tree which is bearing fruit. You can suppress it but it’s bad for you. For the creative people I’ve worked with if they’re not creative they’re miserable, so they have to do it. And there is real joy and pleasure in it, and psychological utility. But that certainly doesn’t mean it’s a conservative strategy for moving through life.” He goes on to give some advice to the aforementioned group, saying “if you happen to be creative… find a way to make money, and then practice your craft on the side, because you will starve to death otherwise. Now for some of you that won’t be true, but it’s a tiny minority” (7).",
      "Building a Walden Pond is helpful for people in many life situations. We’ve talked about its utility for people who are overextended with excessive working hours and material possessions, and for those who need to break the routine and homogenization of their life to build something that helps them reach a more spiritual connection with the world around them. But for creatives, a strategy like FIRE which can help remove them from the hamster wheel of traditional work schedules can save them from the depression and existential angst that comes with not following their passions. At the same time, it helps them pursue what their heart desires without being completely reliant on the unlikely odds of massive immediate success. A songwriter who has FIREd, lives in a paid off house, lives a simple lifestyle, and is able weather a financial storm, is more likely to keep to their craft and write for nothing but their own relation to the muse. How much art would be better if the artist wasn’t reliant on whether or not it would be sold? Would some artists be better off if they weren’t drained by the mental strain of being near starvation?",
      "Solutions for this problem aren’t going to come from exogenous sources any time soon. People who have an urge or a calling to work on something which is novel and unique will have to figure out which constellation of escape plans will work for them. Strategies like FIRE are more likely to be taken up by creative people for this reason, as they are looking for a way in which they can have the time and energy to pursue what is actually meaningful without being completely tied to the result of that endeavor. They need Walden Ponds to get their ideas onto the page, or the canvas, or in front of a VC. Our current all-or-nothing system requires starving artists and a few which are eccentric billionaires. Maybe we should emphasize strategies to reduce the plight of the former to increase the number of the later."
    ],
    image: pareto
  }
];

export default articleList;
