let articleList = [
  {
    title: "Simplicity is a Bottleneck",
    paragraphs: [
      "Are people exaggerating, deceiving, or otherwise being delusional when they say that minimalism changed their life? It seems unlikely from the outside that changing the space a person lives in, or the way they go about their life, could have an impact on the real, core personality and characteristics of that person. For many, the merits of something like minimalism are only visible through practice. Like meditation, spirituality, and other types of eye-roll inducing new age pillars, practitioners ask the public for a leap of faith when trying to change their minds. Perhaps the best way to consider problems like this is with analogy, which can remove context and bias in order to get at the core of something. Luckily for us an analogy for minimalism exists in the world of biology – the Bottleneck Effect.",
      "The Bottleneck Effect describes the change which happens to a population (of animals, fungi, bacteria, whatever) after a sudden and disruptive change happens in their environment. To illustrate this phenomenon in a simple way, let’s imagine that there is a dog pound on an island somewhere in the Pacific Ocean. The dog pound has all types of dogs, including everything from pit bulls to chihuahuas to shih tzus. One day, a volcano erupts on the island, and lava is pouring down towards the pound. In a panic, islanders take the dogs from the pound and board them onto several ships which head to nearby islands, each only large enough to house a fraction of the total number of dogs. By chance, one of the boats fills with only chihuahuas, and heads to an island which is an hour boat ride away.",
      "On this new island, populated by only chihuahuas, every new generation of dog born will look like a chihuahua. Everything dog on this new island will be small, yappy, and soft. Even though these dog’s ancestors come from a much larger genetic pool, the bottleneck effect which their lineage experienced (the volcanic eruption) shrunk the variability in genetic possibilities for these dogs. Extrapolating this to the real world, the bottleneck effect is a big part of why species differ over time. In many cases the products of bottleneck events are populations that are appear to be entirely different than the populations that their ancestors. ",
      "With that in mind, consider what the stated function of minimalism and simplicity movements. They serve as a self-imposed bottleneck which selects for things that are essential and meaningful. Rather than a volcano randomly selecting which traits make it to the future, minimalism selects for things which are meaningful. Things which are excessive and frivolous don’t make it through the bottleneck, which allows the meaningful things to blossom on the other end. When people reduce the size of their living space, the number of things they have to tend to, or the number of hours they spend at jobs they don’t enjoy, they have created a bottleneck that has removed a lot of junk in the population that is their daily life. Over time, new things fill the void left by the cutting out of things that aren’t essential. If one is careful about selecting based on meaning, time spent on cleaning their house that is too big can be used for something like meditation. These changes pile up over time, and, like a population that looks and feels incredibly different from before the Bottleneck event, a person can go through drastic changes as well. "
    ]
  }
];

export default articleList;
